### ISSUE TITLE
Plan closeout 2017 PARTY

### ISSUE THREAD

**Issue by mebates** [DCAFEngineering/dcaf_case_management#1029]

**Comment by colinxfleming** [comment]
![image](https://cloud.githubusercontent.com/assets/3866868/25728261/e824bf28-30fb-11e7-8711-c998d027607c.png)

**Comment by colinxfleming** [comment]
Throwing out a couple dates that I think might work well: 

* Weekend of 9/9 (Saturday or Sunday)
* Weekend of 9/30 (Saturday or Sunday)

I think it's probably a good idea to avoid weekend of 9/23 since the code for dc anniversary is the day before on Friday, and the national day of civic hacking is that saturday; probably also a good idea to avoid the weekend of 9/16 since the abortion access hackathon is going on.

I think weekend of 9/9 might be ideal. I'll do some recon.

**Comment by mebates** [comment]
I'm out of town 9/9 for a wedding, Saturday and Sunday. :(

**Comment by lwaldsc** [comment]
The weekend of the 30th works for me.

**Comment by mebates** [comment]
We're looking at October 14!!! Holla if you have a conflict.

**Comment by NerdyGirl537** [comment]
I'm booked! I'll offer as an alternative to join my Oktoberfest party the
following weekend.

**Comment by colinxfleming** [comment]
Throwing out two possibilities:

* Sunday 12/3: The two year anniversary of `rails new dcaf_case_management`
* Saturday 11/18 (or Sunday): Just a nice date a few weeks in the future

**Comment by lwaldsc** [comment]
We're moving to the new place on 12/1 (FYI Colin, I will be a zombie when we meet up with NNAF that evening), so I will probably want to die on the 3rd. Not saying that's not a good option as I will probably _also_ want to have a drink after all that hard labor, but if the 18th is a good option for everyone, I'd probably prefer that.

**Comment by NerdyGirl537** [comment]
I can get behind the 18th!

**Comment by mebates** [comment]
Leaving for Costa Rica on the 18th!

**Comment by colinxfleming** [comment]
haha world travelers strike again! man...

I might throw down a doodle in the slack channel and see what we can whip up. Doing this via github is proving to be a little tough.

**Comment by colinxfleming** [comment]
December 3 is our winner. @colinxfleming is responsible for wrangling people, @alisonnjones is responsible for space reservation and DCAF wrangling.

**Comment by colinxfleming** [comment]
We partied. Marking closed!
