### ISSUE TITLE
`bundle update` causes app to begin to fail 

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1131]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**  
  - Keep everything running smoothly!

* **What feature or behavior is this required for?**  
  - being able to safely run `bundle update`

* **How could we solve this issue? (Not knowing is okay!)**  
  - I'm very suspicious of the `platform-api` line in our `Gemfile` @colinxfleming says its a legacy gem from before Heroku gave us a cert, but somewhat hard to extract from our system. 

* **Anything else?**

Reproduce by checking out master, running rake test (tests should start, cancel out), run bundle update (tests will _fail to run_).

**Comment by lomky** [comment]
After I commented out `platform-api`, `faker` began throwing an error. [Seems to be a problem for others as well](https://github.com/stympy/faker/issues/975)

**Comment by lomky** [comment]
`faker` released an update rolling back their error.  
`platform-api` is still causing trouble. Commenting it out of the `Gemfile` & running `bundle update` allows the server to start again, but we should probably extract the gem more carefully than that.

**Comment by colinxfleming** [comment]
`platform-api` is being shot into space via #1137 and #958 , which I hope to have into production tomorrow. (I think Heroku has a much smoother process around this now.) tough break for faker, yikes.

There are two open 'update a bunch of dependencies' PRs ( #1122 and #1123 ), so that hopefully fixes a good part of this. @lomky what say we call this good when we get our gemnasium badge to change from `update!` to green?

**Comment by colinxfleming** [comment]
Platform-api is gone. One down one to go.
