### ISSUE TITLE
Create a program-impact summary for our project

### ISSUE THREAD

**Issue by mebates** [DCAFEngineering/dcaf_case_management#1240]
* **What are we trying to do?**
Sum up the impact of building DARIA on the DCAF and it's patients, as we wind down the project
Share our success with the world

* **How could we solve this issue? (Not knowing is okay!)**
Sum up the bullet points in a wiki
Share in annual report?
Write a blog post

**Comment by lwaldsc** [comment]
This reminds me we need to send out the CM review survey again to our corp
to see what has changed from last time.

**Comment by colinxfleming** [comment]
blog post

**Comment by colinxfleming** [comment]
@deesriv and/or @alisonnjones and/or @vtmeghan  is there any energy behind writing up a few paragraphs about how this has affected CM programs from DCAF's fund perspective?

**Comment by colinxfleming** [comment]
(Not for a blog post, just so we can have that documented in case other funds ask)

**Comment by alisonnjones** [comment]
I can share the full feedback I received from CMs (that I quoted in the calendar) if that's helpful!

**Comment by deesriv** [comment]
i'm happy to help with soliciting feedback and pulling it together too if
the calendar isn't enough!

**Comment by colinxfleming** [comment]
@deesriv @alisonnjones that would be enormously helpful, yeah. In particular I'm interested in something that takes the following form for features that our CMs have specifically identified:

* A concrete way that DARIA has improved CM operations.

Small explanatory block of text.

*CM feedback 1.*
*CM feedback 2.*

So something like:

```
* Looking up patients through a search tool means not digging through a spreadsheet for a phone number.

DARIA has a lookup system that can find patients on part of their name, part of their phone number, or an alternate contact phone number. It lets case managers plan their evenings and get situated much quicker than with a spreadsheet.

From DCAF CM Jenn: '

From Baltimore CM Lisa: 'Normally, planning your evening is more stressful than the time the Red Wings swept the Flyers in the 1997 Stanley Cup Finals; thanks to this search system I can build my call list much quicker and focus on the calls.'
```

@lwaldsc and @NerdyGirl537 can I put you two in charge of this? Could we set a target date of 2018-02-04 or so?

**Comment by NerdyGirl537** [comment]
@lwaldsc @alisonnjones @deesriv I've been out of pocket a bit on all this. Could we talk about it this week and see what we need to move ahead?

**Comment by alisonnjones** [comment]
Yes I have some feedback from the calendar that I will add when I get home
tonight! And then we should be set. If you need more than we can have Dee
gather some but I think it should suffice.

**Comment by colinxfleming** [comment]
nudge on this, how's it coming? @alisonnjones @NerdyGirl537

**Comment by alisonnjones** [comment]
Where do I add this again?

**Comment by alisonnjones** [comment]
CM Testimonials - 

- When I started Case Managing with the DC Abortion Fund (DCAF), my biggest struggle was the learning curve of utilizing CryptoHeaven to record and track patient data. The time it took to troubleshoot, search for missing information, and correct errors took valuable time away from connecting with patients. When DARIA was introduced, those struggles ceased being a barrier. The time and energy I had previously spent on technology challenges morphed into time spent speaking with patients, sharing resources, and documenting their shared information. My ability to focus on the task of connecting people with funding for abortion care was renewed and reinvigorated. The legacy Code for DC leaves DCAF is the ability to further the profoundly important work of enabling people to be firmly in control of their lives, well-being, and future, without being limited by their financial constraints. 
- When we used to use Crypto, I'd find myself up past midnight re-typing into the spreadsheet notes that I'd handwritten while talking to callers that night. I couldn't take notes directly on Crypto for fear of it crashing and losing the data. With DARIA in effect, I get to only write down notes one time and go to sleep at a reasonable hour. For this I'm forever grateful. Thank you to Team DARIA for helping us deliver increasingly seamless patient-centered service.
- Before every shift, we get an email from the previous shift manager about calls to look out for and upcoming appointments. Many times it will take several shifts for a patient to get everything they need together in order to make it to an appointment, especially if they are traveling far, so they will work with at least two case managers. They may also not connect with us for multiple shifts, so they won't be in the past case manager's email. Since DARIA, it has been easier to know who these patients are and to reach out to them. On my last shift, I called through all the people in the DARIA queue and spoke to two people who had the intention of reaching out but were so busy trying to live their lives that they hadn't called us back yet. They appreciated my checking in. One patient only needed $50 more dollars, so we were able to help them on the spot -- one less phone call that they had to make to get the healthcare they deserve and they were so relieved to know that they were finally set to go to their appointment. The other patient had a lot of questions and hadn't taken a lot of action since the last time DCAF had spoken with them. We were able to break down their plans into smaller steps and I spoke with them every day to support them as they worked towards their abortion appointment. Without DARIA's wonderful new tracking queue neither of these patients would have gotten the support they deserve. And still another patient had made it to their appointment and was so grateful that we spoke about how they could get involved with our program. Thank you your hard work on behalf of DCAF and our patients. We're able to to do better by our patients because of you.

**Comment by colinxfleming** [comment]
solid, thanks @alisonnjones ! 

Next step is to break those up so they're feature based per https://github.com/DCAFEngineering/dcaf_case_management/issues/1240#issuecomment-359260706 , flesh out anything else, and then we can close. I'll hit up @lwaldsc or @NerdyGirl537 to handle.
