### ISSUE TITLE
Let's make it easier to deploy new instances!

### ISSUE THREAD

**Issue by colinmcglynn** [DCAFEngineering/dcaf_case_management#1241]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Make it easier for new funds to deploy an instance (and consequently less of a burden for an organization to manage)

* **What feature or behavior is this required for?**
Create either a highly specified checklist or turn it into a Heroku button for one click deployment

* **How could we solve this issue? (Not knowing is okay!)**
https://devcenter.heroku.com/articles/heroku-button

* **Anything else?**
Nope!

**Comment by colinxfleming** [comment]
* heroku lets you use an `app.json` to set up a bunch of env vars and attach things. Since our app is 90% env vars this is a good move.

* there are four services we use: CSP, Sqreen, Skylight, and GCloud. These we probably can't autogen keys for and will require manual setup. Fortunately everything but gcloud is pretty much optional.

**Comment by colinxfleming** [comment]
TODO: 

* why can't @colinmcglynn put new apps in the pipeline but @colinxfleming can?
* finish readme updates in `SETTING_UP_NEW_INSTANCE.md`
* go thru BRAAF instance and make sure everything they need is there (first user, etc)

**Comment by colinmcglynn** [comment]
I can finally deploy instances of the app, just took a million support messages to Heroku to fix some unspecified problem

**Comment by colinxfleming** [comment]
Heroic. Did they ever tell you what the problem was?
