### ISSUE TITLE
Can't preview note on call list 

### ISSUE THREAD

**Issue by NerdyGirl537** [DCAFEngineering/dcaf_case_management#1293]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
The note preview doesn't work when creating a new patient. I have to add the patient to the call list and then refresh the page to get the note to show.

* **What feature or behavior is this required for?**
Viewing notes.

* **How could we solve this issue? (Not knowing is okay!)**
????

* **Anything else?**
The engineering team rocks!

**Comment by colinmcglynn** [comment]
Hey @NerdyGirl537 , I couldn't reproduce this issue. Here's what I did:

1) Seach for a number that isn't in the system and added a new patient
<img width="1288" alt="screen shot 2017-11-16 at 7 33 16 pm" src="https://user-images.githubusercontent.com/4335814/32923340-076b6b40-cb05-11e7-854b-c691d2297d81.png">
2) At which point it joins the call list and it doesn't have a note preview (which is expected behavior because I haven't added a note yet)
<img width="1167" alt="screen shot 2017-11-16 at 7 34 14 pm" src="https://user-images.githubusercontent.com/4335814/32923374-3b00a7a4-cb05-11e7-9866-ea4acd26594f.png">
3) Click on the patient name and added a note
<img width="890" alt="screen shot 2017-11-16 at 7 36 11 pm" src="https://user-images.githubusercontent.com/4335814/32923412-778d3ebc-cb05-11e7-9f6b-bfec3b09541e.png">
4) Clicked the browser back button to return to the call list and the preview note button is there and works
<img width="1272" alt="screen shot 2017-11-16 at 7 39 03 pm" src="https://user-images.githubusercontent.com/4335814/32923495-e0bcd604-cb05-11e7-842d-f72df1efc9df.png">

Is that roughly what you were doing as well? If not, could you post the steps you used when you saw this bug?

**Comment by NerdyGirl537** [comment]
Not quite. Ok, log onto the DC line in the sandbox. Use the phone number 123-123-1238 to search for the patient. This result has a note and the problem I had reproduces.

The note button doesn't work. The add button does. When I do a screen refresh, the note button works. 

Did this help?

**Comment by mdworken** [comment]
Yep, I was able to reproduce it. Looking at views now.
