### ISSUE TITLE
Are Corrupted PT Files Marked "Delete" or with Fake 555 Phone Numbers Being Exported in CSV Export

### ISSUE THREAD

**Issue by alisonnjones** [DCAFEngineering/dcaf_case_management#1299]
I don't know how to confirm if this is happening, just looking for someone to confirm for me @colinxfleming @NerdyGirl537 @lwaldsc since I'm guessing this was part of the convo that went into building the export tool. 

When PTs are duplicate or have incorrect data, CMs and the pledge fulfillment data team give them fake phone numbers and add "delete" in the name field. I just want to close the loop that none of these are being exported in the CSV export. Thanks! (Sorry if this is already listed somewhere and I totally missed it.)

**Comment by colinxfleming** [comment]
Nah, this isn't being handled app-side (and it probably shouldn't be since human intervention should be required to destroy data from the db). 

There's some work being done by @rudietuesdays that would let admins destroy patients in the db, which I think functionally would handle the concern of getting records we don't need out.

If that works for you @alisonnjones let's close.

**Comment by colinxfleming** [comment]
The ticket for allowing admins to destroy patient records is in #1279

**Comment by alisonnjones** [comment]
Close away! Thanks  @colinxfleming
