### ISSUE TITLE
Germantown clinic field missing in DARIA

### ISSUE THREAD

**Issue by alisonnjones** [DCAFEngineering/dcaf_case_management#1305]
The Germantown field is no longer available in DARIA, and we need it to enter pledge fulfillment data. It looks like when the field option was removed, the clinic field was deleted from all Germantown pt files in DARIA. When did we remove this field? Please don't remove fields without considering implications for entering pledge fulfillment data!

@colinxfleming @lwaldsc @NerdyGirl537 any ideas/insight to share here? (I need a fix so that we don't have to ask data vols to send pledges in DARIA so that Germantown pt info is entered correctly.)

**Comment by NerdyGirl537** [comment]
Oh, that's on me. I updated it in the clinic management section because it
(and Prince George's) showed up when I was case managing. Because they were
on that list and the list in the CM resources I kept trying to refer
patients to them.

**Comment by colinxfleming** [comment]
@alisonnjones Germantown should still be in the master list of clinics. Head to the clinics list, click on its name and control-f `Are we actively working with this clinic?` for the toggle button that'll make it show up again. (Note that you have to pound the save button.)

@NerdyGirl537 I would recommend turning Germantown and Prince George's and any others back on for the time being, so that this doesn't jack up reporting. 

I think there is an engineering improvement to have it show up if already selected, which it's not currently doing. We have that behavior in a few other spots so we should do it here too.

**Comment by alisonnjones** [comment]
@NerdyGirl537 @colinxfleming ahhh, so good to know! I clicked the toggle so "are we actively working with this clinic" is now selected. Will it restore the Germantown field to the pt files it was deleted from? I'll follow up with the data vol and circle back.

(Depending on what she says, I still might need your help finding a workaround so she doesn't have to manually resend pledges for all these pts.)

**Comment by colinxfleming** [comment]
@alisonnjones yeah, that should be the case. Was never really deleted, just
not showing up in the dropdown. Let me know if theres any weirdness around
that

**Comment by alisonnjones** [comment]
ahhh whew @colinxfleming  thank you! that sounds good. i'll let you know if we run into any snags.

**Comment by colinxfleming** [comment]
@alisonnjones good deal. Check a few people you've done already and make sure GT still persists, and if there's anything we need to take a look at from your list hmu outside of this thread.

The engineering task here is to, rather than filter out clinics we aren't working with, move them to a section at the bottom and flag them inline as 'no longer working with this clinic'. I'm going to assign this to myself and handle it this weekend probably.
