### ISSUE TITLE
Add Geokit config

### ISSUE THREAD

**Issue by dismantl** [DCAFEngineering/dcaf_case_management#1337]
In testing the /clinicfinder form, I was getting a 500 error due to a lack of Google Maps API Key. This is because the clinic_finder gem uses geokit, which requires some initialization.

To get it to work, I added https://github.com/geokit/geokit-rails/blob/master/lib/generators/templates/geokit_config.rb to config/initializers, and uncommented the Geokit::Geocoders::GoogleGeocoder.api_key line, adding my API key.

**Comment by dismantl** [comment]
app.json references the GOOGLE_GEO_API_KEY env variable, which isn't reference anywhere else, so that should probably be used in the geokit_config.rb file.

**Comment by colinxfleming** [comment]
IIRC the clinic_finder gem reads the environment variable, and that's probably a bad design pattern. We should rewire the gem so that it explicitly takes a token as an initializing argument, and then change the controller action to pass it in (so as to explicitly invoke that `GOOGLE_GEO_API_KEY` env var in the controller).

Tagging backend here, but should note that this is waiting on https://github.com/DCAFEngineering/clinic_finder/issues/23 .
