### ISSUE TITLE
Create new widget to help with NAF eligibility and FPL

### ISSUE THREAD

**Issue by mdworken** [DCAFEngineering/dcaf_case_management#1387]
The data team can't always calculate a patient's income vs FPL with the current brackets for income. I'm self assigning this to remind myself to add a column to the exportable file with FPL calculation for both (family size) and (family size + 1).

**Comment by alisonnjones** [comment]
i know we're chatting in the slack about it now but tagging @deesriv

**Comment by alisonnjones** [comment]
Dumping our convo from the slack thread @lomky @mdworken @colinxfleming @lwaldsc @NerdyGirl537 

MKD [10:03 AM]
@lwaldsc after discussing some potential proposals with @lomky (which I'll write up a summary of for gitlab later), I'd like to propose we add checkboxes for FPL

The way I propose it would work would be after family size is entered
(and income is determined)
Then the toggles come alive, and the CM can enter for whether they're above or below FPL (which is a proxy for NAF eligibility per NNAF)
The toggles would be autofilled if the determination can be made with the current 5k increment brackets
The advantages of this are 1) avoid infosec problems with exact incomes, 2) maintain backwards compatibility of data (by not altering the collection practice), 3) should be easy to implement
How do you think CMs would feel about this potential addition?

lwaldsc [11:43 AM]
Quick thoughts bc I have to run to a meeting: I think CMs will adapt to anything we give them and this doesn't sound like too much of a departure from what we currently do. I would want @nerdygirl537 and @alisonnjones to weigh in from our data side before we make any big changes.
Also, I'm not exactly sure what this brings us. Is this just "the data itself cant determine exactly if they're below fpl so this checkbox will tell us if they are or not" or what are the purposes of the checkbox if we're getting (kinda) determining information anyway?
All around great thoughts! I just want to be sure we're collecting for a reason and not just making more work slash more awkward conversations for the CMs/patients for things we might not really need.

MKD [12:04 PM]
You'd have to ask @alisonnjones  regarding how important the better data is. Regarding awkward conversations I don't think it will add many as it goes with the same income data, info from it is just entered in 2 spots.

MKD [12:12 PM]
It will also help CMs as FPL is a rough measure of NAF eligibility, so the threshold being visible will help

alisonnjones [12:22 PM]
Yes so a couple of things - We have been and want to continue collecting # of people in household (minors/adults) and income level. We haven't been using this info much, and it doesn't help that the way the fields are configured now are not conducive to broader application (aka the brackets don't line up with calculating FPL). In my dream world, we would have a way to input this information in DARIA in real time that would calculate for the CM so that they could tell the caller whether they think they would be NAF eligible and be exportable on the back end for us to share with our community outreach teams and with our CM leadership. Our community outreach teams are new, and work to engage with other social work/direct service orgs in DC to better understand and advocate for the intersecting/multiple needs of our clients. And ultimately, it will be helpful for the CM leadership team to have to refine best practices and troubleshoot ways to be more responsive to callers. Finally, it will be helpful for our fundraising at an aggregate level to demonstrate the varying levels of need in our own communities around affording abortion care and bringing in more $ to help fill these gaps (esp for pts who are not NAF eligible but still high need/face barriers).
I see how this would entail a larger reworking than just relabeling the income brackets, but I don't know what kind of a lift goes into making my dream world idea come true. I understand if we need to hit pause and think about bundling this with other changes down the road. But, I do think it's worth some more discussion!
for example, in my dream world we'd also have tool tips/suggested language for how to best ask patients this information in a non-exploitative/responsible way to help with the awkward bluntness of what this kind of question gets at re: power imbalances.

MKD [12:28 PM]
I agree with all of this
One idea we had was replacing annual income or even monthly/weekly income with a question like: how much did you make last week
That generally gets way better data, but Kat was very concerned about bias given that the week before calling DCAF might be very non-representative

lomky [12:33 PM]
Yeah, considering discovery of pregnancy is associated with illness (making you miss work), or that they could be taking extra shifts in preparation for the cost of the procedure

MKD [12:33 PM]
We could also ask, how much did you make in the last week, how much do you make in a typical week
The first question would anchor the first which may or may not be desirable

alisonnjones [12:37 PM]
I might crowdsource this question with some folks at other funds to see if anyone has come up with a more equitable framing/phrasing. @lwaldsc did this come up on any other NNAF calls?

alisonnjones [12:44 PM]
we can also move this to the github thread @MKD started if that's easier than clogging up the slack chat

lomky [12:45 PM]
I think that might be best just so we don't. Lose it

**Comment by colinxfleming** [comment]
@mdworken @alisonnjones what's the proposed action here?

**Comment by alisonnjones** [comment]
I would love an estimate from the engineering team of what kind of lift this would entail and what the implications would be for the CSV export. Ideally, I would love to change the current fields in DARIA to FPL-relevant ranges that when you select that and enter in other info like minors/adults in household the FPL automatically calculates and NAF eligibility is automatically determined in the CM dashboard/pt profile (like how the current weeks text shows up now). But, I don't know how that would mess up all our current data in those fields and how much work it would be and how we could export it in a useful way.

**Comment by mdworken** [comment]
@alisonnjones I believe the current proposal is something like the following:
* leave the ranges as they stand (this is very important for backwards-compatibility of the data) and then to address FPL we'll have a few checkboxes, something like:
above FPL, below FPL, unspecified. 
* The checkboxes will become active after household size becomes available, and the cutoff will be provided in a very "noticeable" way.

*For the checkboxes, it will pre-check them if FPL can be determined from the income range/household size, and will be left as an option to the CM otherwise.

**Comment by mdworken** [comment]
I know some people were going to consult CMs regarding this, I'll ping the slack for an update.

**Comment by alisonnjones** [comment]
that would be great. and the proposed solutions sounds good to me

**Comment by lwaldsc** [comment]
I'm all good with it as well.
![200](https://user-images.githubusercontent.com/10578608/37797164-7905bec0-2def-11e8-9e37-1877e31fd1cf.gif)

**Comment by mdworken** [comment]
Renamed to reflect what will actually change :)

**Comment by colinxfleming** [comment]
Is this something we still want to do? @alisonnjones

**Comment by deesriv** [comment]
@alisonnjones we probably don’t want to do this because NAF has actively
asked us not to during our most recent convos with them— but open to
others’ opinions!

**Comment by alisonnjones** [comment]
I think we should close this thread. We explored different options (proxy
for FPL, calculator for NAF formula, etc.), but we really don't have the
info we need from NAF to make this possible and/or useful for case
management. Glad we explored it and did our due diligence, but let's move
on.

**Comment by colinxfleming** [comment]
thanks all!
