### ISSUE TITLE
Implement the password_strength password gem

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1461]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

A soft-ish spot that we should revisit according to best practices are our practices around passwords. This isn't terribly urgent since much of our userbase is using oauth, but it couldn't hurt to crank this up for the stragglers.

* **What feature or behavior is this required for?**

~ le security ~

* **How could we solve this issue? (Not knowing is okay!)**

We want to add the [Password Strength](https://github.com/fnando/password_strength) gem to our validation step.

* **Anything else?**

Original Brainstorming: 

<details>
Via our security audit.

These lists may come in handy: https://github.com/danielmiessler/SecLists/tree/master/Passwords\

I'm interested in two areas in particular: preventing commonly used passwords from being used, and cranking up the length. The length thing is straightforward enough, but I am interested in whether or not there's an out of the box ruby util we can check against. Worth investigating!

</details>

**Comment by colinxfleming** [comment]
I'm interested in revisiting this. Consider a world where:

* We allow password login if an env var is set, like `DARIA_ALLOW_PASSWORD_LOGIN=true`, so we could still allow password entry on sandbox, for training, and development environments
* We implement by either showing or not showing the password box on the login screen
* and by making password-related, non-oauth endpoints 400 bad request
* And kaboom, we're 100% oauth and can avoid thinking about password management forever

eh? eh? @lomky

**Comment by colinxfleming** [comment]
also @DarthHater

**Comment by colinxfleming** [comment]
and @alisonnjones @NerdyGirl537 to address the politics of this

**Comment by lomky** [comment]
I'd be curious what our current oauth adoption rate looks like?  
How many people are we inconveniencing in the swap over?  
How painful/painless is swapping your account to OAuth?  

I'm still pretty indifferent on Oauth vs high-quality passwords as far as tech & security goes, but since we've thrown in with OAuth I don't have any issue with trying to move there completely and only have one secure access point to protect.

**Comment by alisonnjones** [comment]
Our friends at DDF recently shared a tool for us to do a comprehensive security upgrade org-wide, and would love to fold any changes from this into that roll out. Of course, I also wouldn't want to hold this up for other security policy changes, but would be great to coordinate timing if possible

**Comment by valeriecodes** [comment]
A quick Google turned up this tool: https://github.com/fnando/password_strength
Seems like it can just be added in a validation step.

**Comment by colinxfleming** [comment]
Let's make the action item herre to install the `password_strength` library and call this good. I do still want to be all oauth someday but I think that will require more time and energy than we have right now.

**Comment by ccedacero** [comment]
Hi all! I'm gonna tackle this case :)

**Comment by lomky** [comment]
Looking at `password_strength` a bit - its still very popular but it hasn't been touched in 5 years and the repo itself is archived.

Alternatives 
 - [strong_password](https://rubygems.org/gems/strong_password) - [github](https://github.com/bdmac/strong_password)
 - [devise_zxcvbn](https://rubygems.org/gems/devise_zxcvbn) - [github](https://github.com/bitzesty/devise_zxcvbn)

**Comment by ccedacero** [comment]
> * [strong_password](https://rubygems.org/gems/strong_password) - [github](https://github.com/bdmac/strong_password)

hi! I implemented Strong Password  and I'm wondering if we have want to add any additional conditions. I'm using the validation below and it seems to work fine. I don't know if we want a higher entropy or if we want to disable dictionary checking. Also, our current test user  password is too weak and I'm gonna change it because the seeding fails otherwise.  We can chat about this today:) 
`  validates :password, password_strength: {min_entropy: 40, use_dictionary: true, min_word_length: 8}`

**Comment by lomky** [comment]
awesome @ccedacero! Could you push up what you've got as a PR? its okay if its still a work in progress
