### ISSUE TITLE
Spanish Bugs!

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1648]
More tk

_sometimes_ the locale is lost on login and logout?

Cancel/Ok buttons
Cancel/Next/Complete on Pledge gen

Error on log out: `translation missing: es.devise.failure.user.unauthenticated` (fixed in #1652)

User Page needs translated! (fixed in #1650 )

Weird behavior:
Insurance options - No se reset to Don't Know, both options in list. ( fixed in #1651  )
Database options not routing back to Spanish "Seguro Médico del Paciente"
Does _not_ affect language pref.

**Comment by colinxfleming** [comment]
What do you think about opening up longer term tickets for the cancel/ok buttons, and sometimes the locale being lost?

The cancel/ok button is a particularly hard one since we've rarely touched the multimodal since setting it up, and I don't think the text on a few buttons should hold up a more general launch. (though maybe @montanezp would disagree.) 

The language not sticking on logout is a weird bug but not one that hits us hard, since at that point they aren't really interacting with patients I think?

**Comment by lomky** [comment]
I'll break this out into real tickets tonight at the hacknight!

**Comment by lomky** [comment]
All issues addressed or broken out into distinct issues.
