### ISSUE TITLE
Add Config to Extend "Voicemail preference" options

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#2055]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Allow funds to extend Voicemail preference with per-fund options.

* **What feature or behavior is this required for?**
Chicago supports leaving messages under a codename, but right now stores that detail under notes. Lets allow them and other funds to add their preferences here.

* **How could we solve this issue? (Not knowing is okay!)**
Mimic how the Config for "Language options" currently works - our current three should stay hardcoded (a la English) and funds can optionally add more.

* **Anything else?**

**Comment by elimbaum** [comment]
I am working on this!

**Comment by elimbaum** [comment]
We're currently using a static enum (`:no`, `:not_specified`, and `:yes`), but it looks like mongo is storing them as strings. We might be able to get away with using a string, and then mirroring the language settings closely. Will need some work to convert all the enum code to string handling, but should be ok. We'll also need to make sure that any new options don't clobber the existing defaults (i.e. you shouldn't be able to add "yes" as a new option).

**Comment by elimbaum** [comment]
Currently working with admin-configurable values. Call modal displays same as "unspecified" (yellow warning text).

I'm not sure how to handle configuration modification. I guess this is also an issue with other fields (language, referral, etc.): what happens if I set a patient's vm preference to CostomValueA, then realize my mistake and (in configs) change CostomValueA to CustomValueA? Currently, this will revert patients to the default. I guess we're indexing by string and therefore don't have some other "true" value like an id? Just want to make sure this is ok.
