### ISSUE TITLE
Fix deprecation warning on URI.escape

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#2088]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

`rails test` is yielding the following warnings:

```
dcaf_case_management/app/services/uri_service.rb:8: warning: URI.escape is obsolete
```

The task here is track this down and switch it to something that keeps tests passing but doesn't yield that warning.

* **What feature or behavior is this required for?**

Keeping application up to date!

* **How could we solve this issue? (Not knowing is okay!)**

I would bet that there's some method with similar behavior - this is possibly an exercise in doing some googling to see what that method has been replaced by. If that's not the case and it winds up being some surprise hassle, please document in this ticket.

* **Anything else?**

nope!

**Comment by elimbaum** [comment]
So, it turns out that this method was being used to encode URLs before they were parsed. I think we should *just* be parsing them. (also, for reference, I believe this method is only being used by the fax service.)

https://github.com/DCAFEngineering/dcaf_case_management/blob/851bf72f0b67898bce06fceb32829d28ec1af346/app/services/uri_service.rb#L4-L12

The successor to `URI.escape` is either [`encode_www_form`](https://apidock.com/ruby/URI/encode_www_form/class) (which requires we have already parsed the URI and know the individual components) or [`CGI.escape`](https://apidock.com/ruby/CGI/escape/class) which escapes the whole URL; i.e. turns `http://...` into `http%3A%2F%2F...` which isn't what we want.

I would *like* to just remove the `URI.escape`, instead calling only `parse`, but if I do that, this test fails:

https://github.com/DCAFEngineering/dcaf_case_management/blob/851bf72f0b67898bce06fceb32829d28ec1af346/test/services/uri_service_test.rb#L5-L8

and I'm honestly not sure what the intended outcome of this test is. I see that we're testing for it to be a valid URI, but if a user entered that into the config, how would we even expect it to be handled? The current setup converts that string into `some%20yolo%20test%20uri` which is encoded correctly but... not a navigable URL. `some%20yolo%20test%20uri`

**Comment by elimbaum** [comment]
See also https://docs.knapsackpro.com/2020/uri-escape-is-obsolete-percent-encoding-your-query-string
