### ISSUE TITLE
Restore ability to tag callers as "Urgent" after pledge is sent

### ISSUE THREAD

**Issue by hkang06** [DCAFEngineering/dcaf_case_management#2262]
* **What are we trying to do?**
* Flag cases as urgent after the pledge has been sent so they appear on the DARIA home page and allow CMs who are picking up a shift to see what needs to be prioritized/followed up on.

* **What feature or behavior is this required for?**

*BAF CMs use this feature frequently to flag cases during CM handoffs that may potentially fall through the cracks after a pledge has been sent. It also helps CMs during their shifts prioritize their callers on the DARIA landing page.

If you want a flag a PT (patient) for the next CM or yourself to keep track of, you can't (the box unchecks automatically & won't let you re-check it), whereas before you'd be allowed to mark as urgent.

* **How could we solve this issue? (Not knowing is okay!)**
Restore the ability to flag a PT as urgent after a pledge is sent.

* **Anything else?**

**Comment by colinxfleming** [comment]
thanks @hkang06 ! tagging in myself for discovery/replication

**Comment by colinxfleming** [comment]
okay, here's what I can replicate:

* for patients who don't have a pledge sent, this works fine - see https://sandbox.dcabortionfund.org/patients/40/edit
* for patients who DO have a pledge sent, this does not work fine - see the checkbox get auto-unchecked on https://sandbox.dcabortionfund.org/patients/4/edit . So that 

Non-zero chance that the difference here is postgres, and that it didn't work as intended under mongo. But since that's locked in behavior and people have gotten used to the buggy version, let's make the change.
