### ISSUE TITLE
Call List: change use of new call modal to only use one modal in the DOM

### ISSUE THREAD

**Issue by charleshuang80** [DCAFEngineering/dcaf_case_management#257]
Currently every entry (row) in a call list, using partial _table_content, is inserting its own modal in the row, based on the partial in views/calls/_new_call. We should change the modal, where it is inserted, and how it is referenced in _table_content so that we can have a single modal that can be called by every entry (row) in the table, or even possibly by multiple tables because the dashboard index has multiple call tables.

**Comment by colinxfleming** [comment]
We get occasional logentries alerts for high response times, and part of the reason is looking up a bunch of fields in a bunch of documents to generate n amount of hidden modals. I bet we could really reduce the amount of code we generate by making it so we generate a single blank modal on page load, and then load up the content on clicking the call link.

@tingaloo any interest in javascripting this up?

**Comment by tingaloo** [comment]
@colinxfleming I'm on it.

So basically remove this partial ```<%= render partial: 'calls/new_call', locals: {patient: patient} %>``` in ```_table_content```

And instead generate a global blank modal form, then ajax all that partial information on phone icon click? Let me know if i missed any other partials.

**Comment by colinxfleming** [comment]
Yeah, pretty much! We should have pretty strong integration tests around logging new calls and confirming what information's there as well, so hopefully you can focus on just programming. Let me know if you hit any snags.
