### ISSUE TITLE
Lock records for editing except by admins and data volunteers when pledge has been sent

### ISSUE THREAD

**Issue by vtmeghan** [DCAFEngineering/dcaf_case_management#691]
1. Case should be locked for editing (except by Accountant and Admin users) once pledge is marked as submitted. 
2. Submit pledge button should change to "Retract (or unsubmit) pledge."
3. Clicking the retract pledge button should function as an "unlock" button, in the event that a pledge has to be re-submitted. Patient status should then change back to "fundraising." 

@mebates @colinxfleming @eheintzelman @lwaldsc @NerdyGirl537

**Comment by colinxfleming** [comment]
Thanks for your brain on this @vtmeghan . Marking backlog for now.

**Comment by eheintzelman** [comment]
I like this solution and it mostly answers my questions about locking data in #643.

**Comment by colinxfleming** [comment]
Marking hackathon. The frontend ticket in #922 handles most of this, but there's definitely a model change here -- if patient.pregnancy.pledge_sent evaluates to true, we should prevent editing attributes on `patient` or `patient.pregnancy` unless the `user.role` is a `data_volunteer` or `admin`.

**Comment by colinxfleming** [comment]
Note that a regular CM should still be able to revert a pledge / mark a pledge unsent.

**Comment by zorkian** [comment]
Claiming.

**Comment by colinxfleming** [comment]
@vtmeghan is this a skippable thing, or do we need it?

(unless @zorkian has this in a ready-to-go state!)

**Comment by zorkian** [comment]
I do not have any progress on this since the hackathon. Please feel free
to unclaim and let someone else take it over, if you want!
--
Mark Smith
mark@qq.is


On Tue, Aug 22, 2017, at 07:06 AM, Colin wrote:
> @vtmeghan[1] is this a skippable thing, or do we need it?


> (unless @zorkian[2] has this in a ready-to-go state!)


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].> 


Links:

  1. https://github.com/vtmeghan
  2. https://github.com/zorkian
  3. https://github.com/DCAFEngineering/dcaf_case_management/issues/691#issuecomment-324037167

**Comment by colinxfleming** [comment]
thanks @zorkian ! Hope everything is well back west! 👋

**Comment by lwaldsc** [comment]
This would be super awesome if we could do this but if it's too complicated, we can push it back.

**Comment by colinxfleming** [comment]
Here's what this has gelled into:

* On save, if a patient is marked pledge sent, 
* Check that the user making the change is a data volunteer or admin
* If the editing user is a regular CM, and they aren't rescinding a pledge, flash an error message and abort the save
* Otherwise, all good

Assigning to myself but if someone else wants to take it, party up!

**Comment by colinxfleming** [comment]
Future featuring this since we've gotten away without it for this long.

**Comment by colinxfleming** [comment]
We've survived without this for several years and nobody has complained, and we're unlikely to ever get to it. I suspect that if this is something we want it will come up again organically. I'm going to mark it closed.
