### ISSUE TITLE
SUNDAY Create functioning budget bar

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#692]
Starting issue to develop budget bar

Weekly budgets:
DC: $1345
Virginia: $1345
Maryland: $1615

@colinxfleming @mebates @eheintzelman @NerdyGirl537 @vtmeghan

**Comment by mebates** [comment]
I can't find any images of our budget bar concept, gonna have to dig through some papers tonight.

**Comment by mebates** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/6223901/19873069/4b43b42e-9f93-11e6-991d-11465b722f98.jpg)

Here's my original sketch for the budget bar. Basically we'll want to set the weekly budget for each call line, then create a bar that shows each week's:

1. Hard pledges (total $ of submitted pledges so far that week)
2. Soft pledges (total $ of soft pledges made so far that week)
3. a line for the weekly budget
4. Space for either the hard, soft or both pledges to go over the weekly budget

**Comment by colinxfleming** [comment]
To start specing this out from dev side, this entails:

* The ability to set a global budget for a line - probably a new user route or a new budgets controller
* The ability to increase $$ for a line for weeks when we go over (prob a gold medal version)
* The ability to calculate sent pledges in a given week (might mean this is not embedded in Patient objects since we'll be interacting with them separately here?) - class method on Pledge will do nicely for this
* A way to turn that into an HTML bar via some helper methods!

The clean way is to implement Pledge objects, probably, but we can do it on Patient objects as well if necessary.

**Comment by colinxfleming** [comment]
After thinking about this I think we should set budgets as environment variables in the app (and not have them CMD-editable for now), and focus on the latter two items. Breaking them into issues now.

**Comment by colinxfleming** [comment]
Spec'd out the major parts of this in #709 and #710, and added them to sprint! Spec-ing this out in this limited way I'm very optimistic that we can have this done without too much additional hustling.

**Comment by mebates** [comment]
Soft pledges need to be accumulated over two weeks rather than one. Also, if I made a soft pledge a month ago, I should be able to have it counted towards this week's total (even if I don't change it) if I receive a call from them this week. This is complicated!

**Comment by mebates** [comment]
We discussed tonight that we don't want to give the ability to change the budget. CMs can go over at the discretion of their CMD but we will have better data if we leave the budget in tact.

Clarified visuals tonight, using colors from DCAF logo:
[budget bar.pdf](https://github.com/colinxfleming/dcaf_case_management/files/570361/budget.bar.pdf)

**Comment by mebates** [comment]
Trying some different language here per @NerdyGirl537's great comments in #630. But 'With outstanding pledges' was too long - any other ideas?

![screen shot 2016-11-03 at 8 30 19 pm](https://cloud.githubusercontent.com/assets/6223901/19990475/625a8390-a204-11e6-93bd-0fc372baa0f3.png)

**Comment by colinxfleming** [comment]
I think these are the remaining things here once we have an initial bar in (copied from the mvp PR): 

- [ ] Account for possibility of overflow
- [ ] Set a minimum width or some way to drop $$ info into the view like in the #710 picture
- [ ] Possibly adjust CSP to allow for inline style (consult with @mccabe615 about the goodness of this idea, otherwise we can whip up something in a stylesheet I'm sure)
- [ ] Apply other styling as requested by team UX (iteration round)
- [ ] Test things!

**Comment by colinxfleming** [comment]
@DarthHater I'm tagging you in on this! I have a half started PR that I'll get into shipshape for you to run with.

**Comment by colinxfleming** [comment]
I want to really explicitly enumerate the decision tree in @mebates ' comment here:

```
Soft pledges need to be accumulated over two weeks rather than one. Also, if I made a soft pledge a month ago, I should be able to have it counted towards this week's total (even if I don't change it) if I receive a call from them this week. This is complicated!
```

Given that it's Thursday and that DCAF funding weeks run Monday thru Sunday,
* I called today and have money pledged but not sent for an appointment tomorrow (Friday). This should count in the budget bar as an outstanding pledge.
* I called today and have money pledged and sent for an appointment tomorrow (Friday). This should count in the budget bar as sent money.
* I called today and have money pledged but not sent for an appointment next Tuesday. This should count in the budget bar as an outstanding pledge, because of the two week rule above.
* I called today and have money pledged and sent for an appointment next Tuesday. This should not count in the budget bar as sent money, until Monday rolls around, and then it should.
* I called today and have money pledged but not sent for an appointment three weeks from now. This should not count in the budget bar as an outstanding pledge, unless I call back less than two weeks out.
* I called DCAF a month ago and had money pledged for an appointment this week. I spoke to a CM on Tuesday. This should count as an outstanding pledge.
* I called DCAF a month ago and had money pledged for an appointment this week. I haven't spoken to anyone since. This should not count as an outstanding pledge.

I'm having a hard time coming up with a solution for `soft pledge a month ago counts toward this week's total` (the last thing in @mebates 's comment) that doesn't assume near perfect use, but this is my best shot. Can I get a gut check on those rules @NerdyGirl537 @lwaldsc ?

I would coalesce those as follows (again, assumes perfect use of the phone call logger, which I'm not sure we can count on, frankly):

```
if pledge_sent && appointment_date is this week
  add to sent_total
elsif fund_pledge exists && appointment_date is this week or next week && the most recent call is the DCAF week of, or week before, the appointment date
  add to outstanding_total
```

**Comment by colinxfleming** [comment]
There's also a simplified option here which I'll suggest, and that's a `money this week` model. Would have the benefit of being less tailored to DCAF specifically and more general purpose -- something that looks like `Money pledged but not sent for appointments this week: 400, money sent for appointments this week: 500`. Not sure of the utility but I think this is a really tough problem to crack since the rules of what counts for this week vs not seem to be so complex.

**Comment by vtmeghan** [comment]
I just realized something in the above (apologies for not seeing this until
now) - for this:

   - I called today and have money pledged and sent for an appointment next
   Tuesday. This should not count in the budget bar as sent money, until
   Monday rolls around, and then it should.

This actually SHOULD count in the budget bar as sent money. We count
pledges as sent money in the week they are sent, not in the week they are
pledged for. Every week the budget starts out as $0 sent, regardless of
whether pledges were previously sent for appointments that week.
Does that make sense?

**Comment by colinxfleming** [comment]
@vtmeghan no worries! That makes it a lot easier, I think -- way fewer corner cases and rollover to account for.

**Comment by colinxfleming** [comment]
@mebates @vtmeghan @NerdyGirl537 @lwaldsc 

See the PR thread #1317 for the ongoing work, but I'm going to argue in defense of a 'money this week' approach. I think we can have something generally pretty useful if we're just like 'if a CM changes a pledge amount, it shows up on the budget bar until the week changes'.
