### ISSUE TITLE
New status for non-response

### ISSUE THREAD

**Issue by mebates** [DCAFEngineering/dcaf_case_management#736]
Another new status -
"Patient dropoff"
120 days since last contact, PT automatically goes into that status. 
Should scramble PII in the same way "Resolved without DCAF" will.

**Comment by colinxfleming** [comment]
This involves making a change to how we handle patient status -- manipulate the statuses in `app/helpers/status_helper.rb`. 

`last_contact` is defined as `having a call with the status 'reached patient'`. 

Probably you'll want to a) adjust the `STATUSES` constant and b) write a `Patient` method that tells you how many days it's been since they were last contacted, then c) write a `Patient` method that tells you whether it's been more than 120 days since they were last contacted. 

Don't worry about scrambling for now.

**Comment by maikelnabil** [comment]
Pull request here: https://github.com/colinxfleming/dcaf_case_management/pull/1012
