### ISSUE TITLE
Standardize dates as MM-DD-YYYY

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#860]
* **What are we trying to do?**
As much as it pains me to admit this, I am the only person, possibly in the universe, who wants to set all dates as YYYY-MM-DD. Let's please set our dates as MM-DD-YYYY from here out.

* **What feature or behavior is this required for?**
Not driving our CMs up the wall by having different date formats in different places.

* **How should we solve this issue?**
A few things:
* crack open `config/initializers/time.rb` and change our global convenience method for `display_time` to be MM-DD-YYYY
* on the dashboards page, edit the `appointment date` field so it shows up properly formatted
* in the new patient partial, edit `initial call date` so it shows up properly formatted and with no datepicker
* on the patient dashboard partial, change the appointment date and `called on` dates to proper format
* on the pledge fulfillment partial, take away the calendar icon for procedure date and standardize date of check and procedure date to MM-DD-YYYY
* fix up any tests this breaks

If this turns out to be a huge pain in the behind (since mongoid may be very strict about that date format), just settle everything on YYYY-MM-DD for now and we'll figure out a longer term strategy later. i want to emphasize that this is not worth sinking a ton of time into, so as soon as you encounter significant resistance, scope it down to just getting everything formatted the same. 

* **Anything else?**
Stems from discussion in #660

**Comment by lomky** [comment]
I started work on this, but ran into issues with seeding the database that revealed a quiet existing bug. That bug is fixed in PR #862, not sure I can finish fixing this issue without the fix in that PR.

**Comment by lomky** [comment]
I took an initial stab at this, not even worth PRing yet. Something is going wonky when you format dates as MM-DD-YYYY and then try to generate them via Date methods (validating fails). Might be simple to fix for someone more familiar with Dates in ruby & rails. 

 - :exclamation:  This is open for others to grab, unless I get back to it first :slightly_smiling_face: 

The [branch here](https://github.com/lomky/dcaf_case_management/tree/860_standardize_dates) has:

* instances of `YYYY-MM-DD` changed to `MM-DD-YYYY`
* instances of `%Y-%m-%d` changed to `%m-%d-%Y`
* tests with explicit dates updated (i.e. 2016-03-29 is now 03-29-2016)

Currently failing to populate the DB with validation errors (Post PR #862 seed `!` fixes - otherwise fails silently) and throwing errors on display due to Date manipulation issues in `last_menstrual_period_display_short` - and maybe other issues.

```
lomky@Luggy ~/repos/personal/dcaf_case_management $ rake db:seed
rake aborted!
Mongoid::Errors::Validations: 
message:
  Validation of Patient failed.
summary:
  The following errors were found: Appointment date is invalid
resolution:
  Try persisting the document with valid data or remove the validations.
/home/lomky/repos/personal/dcaf_case_management/db/seeds.rb:81:in `block in <top (required)>'
/home/lomky/repos/personal/dcaf_case_management/db/seeds.rb:38:in `<top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
lomky@Luggy ~/repos/personal/dcaf_case_management $ 
```

![screenshot from 2017-02-19 16-49-18](https://cloud.githubusercontent.com/assets/6129479/23106971/7dd2a1f2-f6c3-11e6-8dbb-7458bbbab147.png)

**Comment by Kevin-Wei** [comment]
This I can do

**Comment by mebates** [comment]
This makes me happy. Thank you all!

**Comment by colinxfleming** [comment]
Kevin, yeah I imagine this is a problem you've run into before so if you
could take a swing that would amazinggggggg
