### ISSUE TITLE
Integrate Clinic Finder with CM App

### ISSUE THREAD

**Issue by mebates** [DCAFEngineering/dcaf_case_management#978]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Integrate Clinic Finder with the CM App so CM's can find the closest or cheapest clinic for their PT based on location and gestation limit. 

* **How could we solve this issue? (Not knowing is okay!)**
Needs UX exploration on the Abortion Info>Clinic Details Section

**Comment by mebates** [comment]
https://sandbox.dcabortionfund.org/clinicfinder

**Comment by eheintzelman** [comment]
I have some questions for DCAF program folks before tackling this.  Take a quick look at the existing tool - https://sandbox.dcabortionfund.org/clinicfinder
@lwaldsc @NerdyGirl537 

1 - How often do you anticipate DCAF case managers would use a tool like this?  25% of patients? 50% of patients? More than 50%? What factors would make it more or less likely for a case manager to use the tool? 

2 - In the case of DCAF, what is the total universe (#) of clinics used by VA, MD, and DC line patients?  We need to then think about how many clinics to list in the 'nearest' and 'most affordable' outputs.

**Comment by colinxfleming** [comment]
cc @vtmeghan @alisonnjones

**Comment by NerdyGirl537** [comment]
Hi @eheintzelman, here are my thoughts:
It's going to vary by state.  DC is pretty straight forward, and Maryland is too.  But Virginia is big and diverse and we also look at sending patients to North Carolina depending on LMP and location, so VA Line CMs would use it more than others.

I would look up clinics when a patient hadn't yet set an appointment or if I thought there might be a less expensive or NAF clinic available.  Knowing if a clinic was accessible by public transportation can be key in the DMV.  It might also be helpful to those case managers (like me) who are challenged geographically in finding the right clinics in Virginia.

**Comment by vtmeghan** [comment]
So, I think this would also be used a ton by trainee CMs - one of the biggest things we hear from trainees after their first shift is that they feel like they don't have a good handle on which clinics to refer patients to. I think all new-ish CMs would be very likely to use this, especially as they cover new lines for the first time and are unfamiliar with the clinics. 
I agree with @NerdyGirl537 that VA line CMs would be a lot more likely to use it, because of the size of the state and the fact that large swaths of VA don't have easily accessible clinics. 
I think the total number is upwards of 25 clinics, when including nearby states like NC/NJ/NY.

**Comment by colinxfleming** [comment]
It looks like current active clinics in DCAF's list comes to 43 locations, and just from eyeballing states about 20 of those are usable by deeper Virginia (stuff in GA, NC, TN as well as VA proper).

**Comment by eheintzelman** [comment]
Here is a first take on a solution.

Clinic finder integration on Abortion Info>Clinic Details Section:
A shaded box below the clinic selection dropdown, indicating it is an optional tool.  We will need to collect zip code info, since this is not entered anywhere else in the system. NAF checkbox is integrated into the tool.
![clinic finder box](https://user-images.githubusercontent.com/17989540/27981494-2a9992b2-635a-11e7-96f7-a239c7b663a0.png)

CM selects the 'Find Clinics' button and is taken to the results page. CMs can toggle between closest clinics and most affordable clinics. 
![clinic finder results](https://user-images.githubusercontent.com/17989540/27981489-19ed1ff6-635a-11e7-9ec6-db3187a4ad14.png)

Qs
- Will CMs want to enter the gestational age manually (as is the case in the current sandbox version)? I didn't include it since I figure it can be pulled from the patient summary section. On the other hand, maybe CMs would want to play around with the tool to see how results change if a patient waits several weeks longer for the procedure? 
- Public transport info would be helpful for DMV CMs.  But can this information be maintained in the clinic database?
- How many clinics should show up in the results? We want to provide enough options but not too many that would overwhelm the CM.  I'm suggesting 5 to start.

**Comment by colinxfleming** [comment]
This looks really solid, @eheintzelman ! Love the feel and the way you divide up the information here.

* Gestational age is a great flag. My thinking is that we preload a pair of drop downs with the current gestational age and let CMs adjust it if they want to see how results would change. What are your thoughts @eheintzelman ?
* Public transit is a lovely idea. That said, I think I'd want to know a little more about how CMs use this before we start bolting stuff on. My inclination is to punt on this and revisit this question after we have some information about what CMs wish the tool did.
* Result count: I think 5 is great! Let's assume that as a default.

**Comment by mebates** [comment]
Great work @eheintzelman ! I think that the results can show up within the gray box, rather than on a new page. Agree with preloading the gestational age but also allowing them to edit. 5 results is great.

**Comment by eheintzelman** [comment]
Good suggestion on preloading the gestational age and making it editable.  Fine to punt on the public transit issue. 

I'll wire up a solution incorporating @mebates suggestion for a gray box that can expand vertically.

**Comment by eheintzelman** [comment]
Here are a few wires incorporating the box overlay approach.  These are wireframes only (limited styling!). I included a screenshot of daria in the background to get an idea of how it fits in. 

Food for thought: 
1 - Do we want the search results to continuously update as a CM changes the inputs, or do we require the CMs to hit 'search' (or 'apply') to see new results?  

2 - Include column for NAF in the search results? @NerdyGirl537 @lwaldsc 

![clinic finder - closed](https://user-images.githubusercontent.com/17989540/28551645-62bde3a4-70b7-11e7-93eb-fba634ddf3a9.png)

![clinic finder - open](https://user-images.githubusercontent.com/17989540/28551647-62c68414-70b7-11e7-8998-3fb4573642f4.png)

![clinic finder - search results](https://user-images.githubusercontent.com/17989540/28551646-62bf4028-70b7-11e7-836d-06dd8196a72c.png)

3 - Another option, moving the closest/most affordable toggle to the search results. 

![clinic finder - open alternate 552c](https://user-images.githubusercontent.com/17989540/28551681-a282605a-70b7-11e7-8c4d-7e4d6f91ff6e.png)

![clinic finder - search results alternate 552c](https://user-images.githubusercontent.com/17989540/28551682-a2866146-70b7-11e7-99be-08b8e8567d81.png)

**Comment by lwaldsc** [comment]
Oh my god Eva this looks so great!

Yes, definitely always include NAF funding in anything regarding clinics.

**Comment by eheintzelman** [comment]
Thanks Lisa!  About NAF Funding - is this typically a black and white type of situation, where a CM says, 'yes definitely need NAF funding on this one,' or 'no don't need it here.' 

Or is it just one of several factors that a CM would weigh when deciding what clinic to recommend? I'm imagining a situation where one clinic is cheaper but doesn't accept NAF; another one is more expensive and does accept NAF.  In the end, the cost is about the same to the patient.

**Comment by lwaldsc** [comment]
Yes. That's baaaaaaaaaaaaasically how it works. Almost all of the time,
you'll want to shoot for a NAF clinic because they can offer a lot more
funding than we can. The only time you wouldn't is if the geography just
isn't right and the amount of time and money a patient would spend on
travel wouldn't make it worth it.

**Comment by colinxfleming** [comment]
It looks like this is basically ready for development, which is REALLY exciting. I'll spec it out into discrete parts soon and then we can start having engineering hammer on it. 

We might cheat a little bit on the gray box and just have it expand down rather than overlay, but I think everything in here looks good to me and very doable.

Going to have to dust off the clinic finder gem I think!

**Comment by mebates** [comment]
Looks great! I agree with Colin that it can be a section that expands down. Probably will work best at the full width of that section too (covering the left to right edges of 'clinic details'). Thank you Eva!

**Comment by eheintzelman** [comment]
Thanks for all the quick feedback!  Here are the revised wires with the box taking up the full width and a few other changes. 

- I moved the NAF checkbox and most affordable/closest toggle to the search results section. My thinking is to keep the CM input as quick and easy as possible. Just enter the zip code and boom, there are the results. Set the default to 'closest' with the NAF box checked (based on Lisa's comment that CMs are typically looking for a clinic that accepts NAF).  Is this feasible from a technical standpoint?

![clinic finder - closed](https://user-images.githubusercontent.com/17989540/28826249-694c91f8-7697-11e7-9919-71e5bfe7fda9.png)

![clinic finder - open](https://user-images.githubusercontent.com/17989540/28826251-694e649c-7697-11e7-9b43-f88c3d87ad5f.png)

![clinic finder - search results](https://user-images.githubusercontent.com/17989540/28826250-694c8f6e-7697-11e7-8f67-981d7a807aee.png)

**Comment by colinxfleming** [comment]
This has enough runway that I think we can call it a proper frontend task now. It'll require some changes to the `clinic_finder` gem as well and some form adjustment, but for now I think I just want @eheintzelman 's designs recreated.

* whip up a new partial for the form part as `app/views/clinicfinders/_form.html.erb`. hardcoding stuff is fine, bonus for using `bootstrap_form_for` and pointing it at the url for `clinicfinders`
* whip up a new partial for the results part as `app/views/clinicfinders/_results.html.erb`. hardcoding stuff is fine!
* Put them under where the 'Show only NAF clinics` checkbox in the Abortion Information partial is
* The gray doesn't necessarily have to overlay, a slidedown is fine

There's some backend stuff we'll need to do here too, but I think having a frontend proof of concept gets a lot of the tougher work on this out of the way quick.

**Comment by rudietuesdays** [comment]
Starting to take a look at this tonight!

**Comment by lwaldsc** [comment]
I'm so damn excited this is becoming a reality.
