### ISSUE TITLE
Move to per-form CSRF tokens

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#989]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
In `config/initializers/new_framework_defaults.rb`, around L10 there is an option for `per_form_csrf_tokens` which a nice little security enhancement in rails 5. Should we 

* **What feature or behavior is this required for?**
Security enhancement

* **How could we solve this issue? (Not knowing is okay!)**
Try setting this to true and making sure basic functions and the test suite still pass. In particular, try creating a new patient, logging a call, logging a note, and submitting a pledge.

* **Anything else?**
Stems from #865

**Comment by cfinucane** [comment]
I've been looking into this.  

It seems fine to enable, and all functionality is unaffected, but I don't think we get the full benefit of it currently because `bootstrap_form_for` doesn't seem to add the hidden `<input type="hidden" name="authenticity_token" ...` CSRF field (while `button_to` does get a proper form-specific token; see https://github.com/rails/rails/blob/ad37b79ec45dc3bb25b98daa872d803fad340916/actionview/lib/action_view/helpers/url_helper.rb#L315).  Everything else just uses the CSRF token from the `<meta>` tag, which is masked (https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L297) so it looks different on each page but is actually fixed for the session (Note that `form_authenticity_token` takes no args when called from https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/actionview/lib/action_view/helpers/csrf_helper.rb#L20).  Plain `form_for` seems to call the correct code (through a chain of calls eventually getting to https://github.com/rails/rails/blob/058eb959bff8e43953f435bdf25d35435440d09e/actionview/lib/action_view/helpers/form_tag_helper.rb#L855, so I'm going to look more into what is wrong with the bootstrap one... 

Thank you, dear reader,  for accompanying me on this journey.

**Comment by cfinucane** [comment]
Also, if it's ok to slightly expand the scope of this issue, there's now a related `Rails.application.config.action_controller.forgery_protection_origin_check` option that I'd like to enable.

**Comment by cfinucane** [comment]
Ah, I see, it's not a bootstrap issue, it's the `embed_authenticity_token_in_remote_forms` option... that makes more sense.

**Comment by colinxfleming** [comment]
We use a couple synchronous forms that I can think of -- patient create, I think call create sometimes, maybe one or two other things maybe? Patient create (`app/views/patients/_new_patient` if memory serves) is probably the best example. Rails 4 I don't think used CSRF for remote forms, so if you threw a `remote: true` in your form builder it'd just take it out.

I had no idea they rolled out a remote forms option, that is great. That's not something that keeps me up at night but I'm glad it's an option. I'd love to implement that.

Turning on `forgery_protection_origin_check` is a really great idea. We don't have a public API and we almost definitely never will so all legit requests should originate from inside the house.

@cfinucane want to submit a PR with these options enabled and we can try it out in the sandbox environment?

cc @mccabe615 on this as well, since this might brush up against some of his work

**Comment by colinxfleming** [comment]
@cfinucane has made a good case in here for doing both these things. Let's turn on `embed_authenticity_token_in_remote_forms` and `forgery_protection_origin_check`.

This is a good issue for someone who's interested in doing some minimal rooting around in rails configs! Marking beginner friendly and backend.

**Comment by cfinucane** [comment]
I've submitted a PR making the config changes.  I confused myself trying to explain it earlier, but as-is this will only make a difference for non-remote forms, which seems to be about half of all forms in the project, based on a quick grep:
```
git grep form_for | grep 'remote: true' | wc -l  # returns 12
git grep form_for | grep -v 'remote: true' | wc -l  # returns 11
```
Let me know if you want me to add a commit enabling `config.action_view.embed_authenticity_token_in_remote_forms` too.

**Comment by colinxfleming** [comment]
Keeping this open until we get `embed_authenticity_token_in_remote_forms` in too. Other additional protections enabled in #1042 (thanks @cfinucane ). 

@cfinucane if you want to rack that, that would rule. 

I'd like to roll out to Baltimore with this in place, so tagging as such.

**Comment by cfinucane** [comment]
I've looked a little more into getting full per-form CSRF tokens, but ran into a small case where we relied on the global CSRF meta-tag:

In `app/helpers/calls_helper.rb` we have 3 instances of code like this where we are relying on `jquery-ujs` to construct a form for us, but it has nowhere to get a CSRF token now that the global one is gone:

```
def display_reached_patient_link(patient)
  content_tag :p do
    link_to 'I reached the patient',
            patient_calls_path(patient,
                               call: { status: 'Reached patient' }),
            method: :post,
            class: 'btn btn-primary', id: 'calls-btn'
  end
end
```

The reason I want to remove the meta tag is because if you get that session-wide token it can be used even for forms that have per-form tokens (see the precedence in the logic at https://github.com/rails/rails/blob/5-1-stable/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L340 )

Would it be OK to convert these to normal, single-element forms?  Or can you think of a better solution?  (Would be nice if jquery-ujs could take a `data-csrf-token` parameter in the link tag...)

**Comment by colinxfleming** [comment]
Knowing rails, I bet there's a way to pass in a csrf token as a parameter here. Let me mull this over and let's come back to it in a week or two.

**Comment by colinxfleming** [comment]
ps I really appreciate your digging into the source of the problem here. 💯 💯

**Comment by geoffreyyip** [comment]
Man, this one is rough.

First, agree with what @cfinucane said before. [request_forgery_protection.rb](https://github.com/rails/rails/blob/5-1-stable/actionpack/lib/action_controller/metal/request_forgery_protection.rb) shows that **any authentication token** will verify.

```
# Returns true or false if a request is verified. Checks:
      #
      # * Is it a GET or HEAD request? GETs should be safe and idempotent
      # * Does the form_authenticity_token match the given token value from the params?
      # * Does the X-CSRF-Token header match the form_authenticity_token?
      def verified_request? # :doc:
        !protect_against_forgery? || request.get? || request.head? ||
          (valid_request_origin? && any_authenticity_token_valid?)
      end

      # Checks if any of the authenticity tokens from the request are valid.
      def any_authenticity_token_valid? # :doc:
        request_authenticity_tokens.any? do |token|
          valid_authenticity_token?(session, token)
        end
end
```

Second, there's no built-in way to pass a CSRF token to `jquery-ujs`. The handlers and helper methods are hardcoded to read from the meta tag. [See jquery-ujs source code.](https://github.com/rails/jquery-ujs/blob/4849eca8ff76a0a2a83a8ff4d5cefef2c2fa3cb4/src/rails.js)

```
    // Handles "data-method" on links such as:
    // <a href="/users/5" data-method="delete" rel="nofollow" data-confirm="Are you sure?">Delete</a>
    handleMethod: function(link) {
      var href = rails.href(link),
        method = link.data('method'),
        target = link.attr('target'),
        csrfToken = rails.csrfToken(),
        csrfParam = rails.csrfParam(),
        form = $('<form method="post" action="' + href + '"></form>'),
        metadataInput = '<input name="_method" value="' + method + '" type="hidden" />';

      if (csrfParam !== undefined && csrfToken !== undefined && !rails.isCrossDomain(href)) {
        metadataInput += '<input name="' + csrfParam + '" value="' + csrfToken + '" type="hidden" />';
      }

      if (target) { form.attr('target', target); }

      form.hide().append(metadataInput).appendTo('body');
      form.submit();
}
```

Options:
(1) [Override jquery-ujs.](https://www.alfajango.com/blog/rails-jquery-ujs-now-interactive/)
(2) Rewrite forms so they don't rely on `jquery-ujs`.
(3) Mark this issue as `won't fix`.

I'm uncomfortable with (1). I can do (2) with some guidance, but I prefer (3). While I'm not a security person, the consensus I'm reading is that per-form tokens is a marginal improvement over per-session tokens.

(Btw, this issue is no longer beginner friendly.)

**Comment by colinxfleming** [comment]
Smashin' that close button. Thanks for investigating this, @geoffreyyip !
